"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-&m@&g4kcjmr)y-s8(sit#74*)ij$o4e2@^r!8o#q#6vt5fp(rh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "forum.apps.ForumConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]


# ❌ A09:2021 – Security Logging and Monitoring Failures
# ✅ FIXED: Add axes to the INSTALLED_APPS list
# INSTALLED_APPS += [
#     "axes",
# ]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ❌ A09:2021 – Security Logging and Monitoring Failures
# ✅ FIXED: Add middleware for django-axes
# MIDDLEWARE += [
#     "axes.middleware.AxesMiddleware",
# ]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# ❌ A07:2021 Identification and Authentication Failures
# ✅ FIXED: Add missing password validators to the AUTH_PASSWORD_VALIDATORS list
#  {
#    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
# },
# {
#    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
# },

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "static/"

LOGOUT_REDIRECT_URL = "/accounts/login/"

LOGIN_REDIRECT_URL = "/forum/"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication backend that handles plain text passwords
AUTHENTICATION_BACKENDS = [
    "forum.auth_backend.PlainTextAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# ❌ A09:2021 – Security Logging and Monitoring Failures
# ✅ FIXED:
# AUTHENTICATION_BACKENDS += [
#     "axes.backends.AxesStandaloneBackend",
# ]
# AXES_FAILURE_LIMIT = 5
# AXES_COOLOFF_DURATION = timedelta(minutes=30)
# AXES_LOCKOUT_TEMPLATE = "security/lockout.html"

# LOGGING = {
#    "version": 1,
#    "disable_existing_loggers": False,
#    "formatters": {
#        "security": {
#            "format": "{levelname} {asctime} {name} {message}",
#            "style": "{",
#        },
#    },
#    "handlers": {
#        "security_file": {
#            "level": "INFO",
#            "class": "logging.FileHandler",
#            "filename": os.path.join(BASE_DIR, "security.log"),
#            "formatter": "security",
#        },
#        "console": {
#            "class": "logging.StreamHandler",
#            "formatter": "security",
#        },
#    },
#    "loggers": {
#        "axes": {
#            "handlers": ["security_file", "console"],
#            "level": "INFO",
#            "propagate": False,
#        },
#        "axes.watch_login": {
#            "handlers": ["security_file", "console"],
#            "level": "INFO",
#            "propagate": False,
#        },
#        "axes.watch_logins": {
#            "handlers": ["security_file", "console"],
#            "level": "INFO",
#            "propagate": False,
#        },
#    },
# }
